# This file is covered by the LICENSE file in the root of this project.
name: "pennovation"

# Ian's label tool convention:
# - unlabelled: [0, 0, 0]
# - road: [0, 0, 1]
# - vegetation: [0, 1, 0]
# - building: [1, 0, 0]
# - grass/sidewalk: [0, 0.4, 0]
# - vehicle: [0, 1, 1]
# - human: [1, 0, 1]
# - gravel: [0, 0.5, 0.5]
# - tree_trunk: [0.5, 0.2, 0.2]
# - light_pole: [1, 0.5, 0]

labels: 
  0 : "unlabelled"
  1 : "road"
  2: "vegetation"
  3: "building"
  4: "grass-sidewalk"
  5: "vehicle"
  6: "human"
  7: "gravel"
  8: "tree_trunk"
  9: "light_pole"

color_map: # bgr
  0 : [0, 0, 0]
  1 : [0, 0, 255]
  2: [245, 150, 100]
  3: [200, 40, 255]
  4: [75, 0, 75]
  5: [50, 120, 255]
  6: [255, 0, 0]
  7: [80, 240, 150]
  8: [200, 40, 255]
  9: [30, 30, 255]

content: # as a ratio with the total number of points
  0: 0.1
  1: 0.1
  2: 0.1
  3: 0.1
  4: 0.1
  5: 0.1
  6: 0.1
  7: 0.1
  8: 0.1
  9: 0.1
  

# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent
# for pennovation dataset, all classes are distinguishable and thus not mapped
learning_map:
  0 : 0
  1 : 1
  2 : 2
  3 : 3
  4 : 4
  5 : 5
  6 : 6
  7 : 7
  8 : 8
  9 : 9

learning_map_inv: # inverse of previous map
  0 : 0
  1 : 1
  2 : 2
  3 : 3
  4 : 4
  5 : 5
  6 : 6
  7 : 7
  8 : 8
  9 : 9

learning_ignore: # Ignore classes
  0: True      
  1: False    
  2: False     
  3: False    
  4: False     
  5: False     
  6: False
  7: False    
  8: False    
  9: False    

split: # sequence numbers
  train:
    - 0
  valid:
    - 1
  test:
    - 1
    - 2
