# This file is covered by the LICENSE file in the root of this project.
name: "pennovation-jackle"

# Ian's label tool convention:
# rgb / 255
# - unlabelled: [0, 0, 0]
# - road: [0, 0, 1]
# - vegetation: [0, 1, 0]
# - building: [1, 0, 0]
# - grass/sidewalk: [0, 0.4, 0]
# - vehicle: [0, 1, 1]
# - human: [1, 0, 1]
# - gravel: [0, 0.5, 0.5]
# - tree_trunk: [0.5, 0.2, 0.2]
# - light_pole: [1, 0.5, 0]

labels: 
  0 : "unlabelled"
  1 : "road"
  2: "vegetation"
  3: "building"
  4: "grass-sidewalk"
  5: "vehicle"
  6: "human"
  7: "gravel"
  8: "tree_trunk"
  9: "light_pole"

color_map: # bgr
  0 : [0, 0, 0]
  1 : [255, 0, 0]
  2: [0, 255, 0]
  3: [0, 0, 255]
  4: [0, 102, 0]
  5: [255, 255, 0]
  6: [255, 0, 255]
  7: [127.5, 127.5, 0]
  8: [51, 51, 127.5]
  9: [0, 127.5, 255]

content: # as a ratio with the total number of points
  # raw stats from the data loader:
  #mean values of number points for each class / total points are:
  #[0.1851279  0.44469167 0.07906675 0.20659639 0.04173904 0.03609916
  # 0.00286886 0.00381022 0.         0.        ]
  0: 0.1851279 #  0 : "unlabelled"
  1: 0.44469167 #  1 : "road"
  2: 0.07906675 #  2: "vegetation"
  3: 0.20659639 #  3: "building"
  4: 0.04173904  #  4: "grass-sidewalk
  5: 0.03609916  #  5: "vehicle"
  6: 0.00286886  #  6: "human"
  7: 0.00381022  #  7: "gravel"
  8: 0.0  #  8: "tree_trunk"
  9: 0.0  #  9: "light_pole"

# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent
# for pennovation dataset, all classes are distinguishable and thus not mapped
learning_map:
  0 : 0
  1 : 1
  2 : 2
  3 : 3
  4 : 4
  5 : 5
  6 : 6
  7 : 7
  8 : 8
  9 : 9

learning_map_inv: # inverse of previous map
  0 : 0
  1 : 1
  2 : 2
  3 : 3
  4 : 4
  5 : 5
  6 : 6
  7 : 7
  8 : 8
  9 : 9

learning_ignore: # Ignore classes
  0: True      
  1: False    
  2: False     
  3: False    
  4: False     
  5: False     
  6: False
  7: False    
  8: False    
  9: False    

split: # sequence numbers
  train:
    - 0
  valid:
    - 1
  test:
    - 2
