################################################################################
# training parameters
################################################################################
train:
  loss: "xentropy"       # must be either xentropy or iou
  max_epochs: 150
  lr: 0.01               # sgd learning rate
  wup_epochs: 1          # warmup during first XX epochs (can be float)
  momentum: 0.9          # sgd momentum
  lr_decay: 0.995        # learning rate decay per epoch after initial cycle (from min lr)
  w_decay: 0.0001        # weight decay
  batch_size: 2         # batch size
  report_batch: 1        # every x batches, report loss
  report_epoch: 1        # every x epochs, report validation set
  epsilon_w: 0.001       # class weight w = 1 / (content + epsilon_w)
  save_summary: False    # Summary of weight histograms for tensorboard
  save_scans: True       # False doesn't save anything, True saves some 
                         # sample images (one per batch of the last calculated batch)
                         # in log folder
  show_scans: False      # show scans during training
  workers: 12            # number of threads to get data

################################################################################
# backbone parameters
################################################################################
backbone:
  name: "darknet"  # ['squeezeseg', 'squeezesegV2', 'darknet']
  input_depth:
    range: True
    xyz: True
    remission: True
  dropout: 0.01
  bn_d: 0.01
  OS: 32 # output stride (only horizontally)
  train: True # train backbone?
  extra:
    layers: 21

################################################################################
# decoder parameters
################################################################################
decoder:
  name: "darknet"
  dropout: 0.01
  bn_d: 0.01
  train: True # train decoder?
  extra: False # nothing to add for this decoder, otherwise this is a dict

################################################################################
# classification head parameters
################################################################################
head:
  name: "segmentation"
  train: True
  dropout: 0.01

################################################################################
# postproc parameters
################################################################################
post:
  CRF: 
    use: False
    train: True
    params: False # this should be a dict when in use
  KNN:
    use: False
    params:
      knn: 5
      search: 5
      sigma: 1.0 
      cutoff: 1.0

################################################################################
# classification head parameters
################################################################################
# dataset (to find parser)
dataset:
  labels: "kitti"
  scans: "kitti"
  max_points: 150000 # max of any scan in dataset
  sensor:
    name: "HDL64"
    type: "spherical" # projective
    fov_up: 3
    fov_down: -25 
    img_prop:
      width: 2048
      height: 64
    img_means: #range,x,y,z,signal
      - 12.12
      - 10.88
      - 0.23
      - -1.04
      - 0.21
    img_stds: #range,x,y,z,signal
      - 12.32
      - 11.47
      - 6.91
      - 0.86
      - 0.16
